name: Run tests for web runners
description: Action for run flutter test for web runners(@uuv/cypress, @uuv/playwright, etc)
inputs:
  node-version:
    required: true
    description: Nodejs version
  runner-name:
    required: true
    description: Targeted runner
  options:
    required: false
    description: test additional options
    default: ""
runs:
  using: "composite"
  steps:
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
        path: |
          node_modules
          packages/assistant/node_modules
          packages/docs/node_modules
          packages/a11y/node_modules
          packages/runner-commons/node_modules
          packages/runner-cypress/node_modules
          packages/runner-playwright/node_modules
          packages/vscode-extension/node_modules
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: packages
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - run: npm ci
      shell: bash
    - run: npx nx e2e-test:run ${{inputs.runner-name}} --verbose -- ${{inputs.options}}
      shell: bash
